### ISSUE TITLE
Array is expected

### ISSUE THREAD

**Issue by KES777** [brainfoolong/form-data-json#10] opened 2021-09-17 18:37 UTC
**Describe the bug**
I expect array for multiple values, but hash is returned

**To Reproduce**
```html
<form>
	<input name = "docn">
	<input name = "docdate">

	<input name = "client[name]">
	<input name = "client[edrpou]">

	<input name = "client[phone][]">
	<input name = "client[phone][]">
	<input name = "client[phone][]">


	<input name = "client[email][]">
	<input name = "client[email][]">

	<select name="client[status][]" id="cars" multiple>
	  <option value="volvo">Volvo</option>
	  <option value="saab">Saab</option>
	  <option value="opel">Opel</option>
	  <option value="audi">Audi</option>
	</select>

	<input type="checkbox" name="scales[]" checked value="77">
	<input type="checkbox" name="scales[]">
</form>

```

```javascript
FormDataJson.fillFormFromJsonValues($("form")[0], 
  {docn : 'asdf', docdate: 'addd', client: { name: 'asdf DDD', phone: [ 'zzzz', 'dd' ] } }, 
  new FormDataJsonOptions({ unsetAllInputsOnFill: true }) 
)
```

![image](https://user-images.githubusercontent.com/799021/133837695-b362a5e1-b9c9-4c12-a425-c4eb2fac1481.png)

**Comment by brainfoolong** [comment] 2021-09-17 18:48
Thanks for the bug report. I can confirm that there is currently no array return for numeric indexed objects, that should obviously be an array. I will fix this.

**Comment by brainfoolong** [comment] 2021-09-18 18:14
Ah, this may take a while longer as expected to fix this. It's easy to fix them in the first place, but it does not incorparate with the counterpart (fillFromJson and toJson) well, because this internal process does handle some things very special when a real array is passed. I have to refactor that a bit and do some more tests with this.

**Comment by brainfoolong** [comment] 2021-09-26 18:33
This error should be fixed in the new pre-release.

**Comment by KES777** [comment] 2021-09-27 13:47
fixed

**Closed** 2021-09-27 17:54 UTC
Labels: bug
